import type { Metadata } from "next";
import "./globals.css";
import ThemeWrapper from "@/providers/ThemeWrapper";
import { Toaster } from "@/components/shadcn/Toaster";
import Header from "@/components/shared/header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body>
        <ThemeWrapper>
          <Toaster />
          <Header />
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
